move to using stow

diff --git a/.config/shell/aliasrc b/.config/shell/aliasrc
--- a/.config/shell/aliasrc
+++ b/.config/shell/aliasrc
@@ -1,5 +1,41 @@
 #!/bin/bash
 
+# For using gnu stow for dotfile management
+alias stowit='stow --adopt --target=$HOME .'
+
+alias musicplay='mpd; mpd-discord-rpc>>/dev/null &; ncm'
+
+alias fman='compgen -c | fzf-tmux | xargs man'
+
+# Helpful aliases
+alias c='clear' # clear terminal
+alias l='eza -lh --icons=auto' # long list
+alias ls='eza -1 --icons=auto' # short list
+alias ll='eza -lha --icons=auto --sort=name --group-directories-first' # long list all
+alias ld='eza -lhD --icons=auto' # long list dirs
+alias lt='eza --icons=auto --tree' # list folder as tree
+alias un='$aurhelper -Rns' # uninstall package
+alias up='$aurhelper -Syu' # update system/package/aur
+alias pl='$aurhelper -Qs' # list installed package
+alias pa='$aurhelper -Ss' # list available package
+alias pc='$aurhelper -Sc' # remove unused cache
+alias po='$aurhelper -Qtdq | $aurhelper -Rns -' # remove unused packages, also try > $aurhelper -Qqd | $aurhelper -Rsu --print -
+
+# Directory navigation shortcuts
+alias ..='cd ..'
+alias ...='cd ../..'
+alias .3='cd ../../..'
+alias .4='cd ../../../..'
+alias .5='cd ../../../../..'
+
+# Always mkdir a path (this doesn't inhibit functionality to make a single dir)
+alias mkdir='mkdir -p'
+
+alias cat="bat -pp"
+
+#code as codium (flatpak)
+alias code="codium"
+
 alias replasma="kquitapp5 plasmashell && kstart5 plasmashell"
 alias replasma2="killall plasmashell && kstart5 plasmashell"
 
@@ -9,13 +45,12 @@ alias bpkga="pacman -Slq | fzf --preview 'pacman -Si {}' --layout=reverse"
 alias levelup="sudo pacman -Syu && yay -Syu"
 alias yadl="yt-dlp -x --audio-format mp3"
 
-# alias bluebird="dumbpython /home/senku/dev/yajurveda/bluebird/main.py download"
-# alias bb="cd /home/senku/Music && bluebird"
-alias bb="cd /home/senku/Music && dumbpython -m spotdl download"
+alias bluebird="dumbpython -m spotdl download"
+alias bb="cd /home/senku/Music && bluebird"
 
-alias ls="ls --color=auto"
 
 alias nv="nvim"
+alias vi="nvim"
 
 alias dumbpython="/home/senku/.development/dumbpython/bin/python"
 alias dumbpip="/home/senku/.development/dumbpython/bin/pip"
@@ -38,7 +73,7 @@ alias ytdl-in-mkv="yt-dlp -f 'bestvideo[height=1080]+bestaudio/best' --merge-out
 
 alias live-alan-becker="gum spin -- mpv 'https://www.youtube.com/@alanbecker/live'"
 
-alias anime="ani-cli"
+alias anime="dumbpython -m fastanime"
 
 alias tmux="tmux -u"
 
@@ -54,9 +89,10 @@ alias arts="while true; do chafa ~/Pictures/xenotrip/\$(ls -1 ~/Pictures/xenotri
 
 alias amegakure-mount="sudo mount /dev/nvme1n1p4 /mnt/amegakure"
 
-alias lt='ls --human-readable --size -1 -S --classify'
+# alias lt='ls --human-readable --size -1 -S --classify'
 
-alias mirror-phone='scrcpy --shortcut-mod=ralt -S'
+alias phone-mirror='scrcpy --shortcut-mod=ralt -S'
+alias phone-otg='scrcpy --shortcut-mod=ralt --otg'
 
 alias bonsai="cbonsai -ilS -L 70 -m 'talk is overrated'"
 alias bonsai-no-sleep="cbonsai -il -L 70 -m 'talk is overrated'"
@@ -147,10 +183,35 @@ yotest() {
 
 
 
+# NOTEL this is from someone else i found a reddit post
 # I used something like that until I decided to automatically cd to the mounted path, and unmount via path as well:
 udm() {
     cd "$(udisksctl mount -b "$@" | tee /dev/stderr | sed 's/.* at \(.*\)$/\1/')"
 }
 udum() {
     udisksctl unmount -b "$@" || udisksctl unmount -p "$@"
+}
+
+
+ntest() {
+  choice=$(printf "Python\nGo\nText\nEtc" | fzf-tmux --prompt="Choose a file type: ")
+
+  case $choice in
+    Python)
+      nvim ~/dev/test.py
+      ;;
+    Text)
+      nvim ~/dev/test.txt
+      ;;
+    Go)
+      nvim ~/dev/test.go
+      ;;
+    Etc)
+      nvim ~/dev/test.md
+      ;;
+    *)
+      echo "Invalid choice. Exiting."
+      exit 1
+      ;;
+  esac
 }
